### PR TITLE
Added new 'Simple searchable' template

### PR DESCRIPTION
**Pull request by zxuwen**
Hi, 

I added a new template named 'simple-searchable'. Has some different styles and a simple js search field for navigation contents. Reran tests to generate sample docs...

screen shot 2016-04-22 at 7 07 56 pm

### CODE REVIEW

**Comment by reloaded** [comment]
Instead of creating a third template, can this be integrated into the angular-template?

**Comment by zxuwen** [comment]
I thought the point was to offer people more choice! Styling changes are a personal preference, didn't want to make any assumptions...

**Comment by reloaded** [comment]
I guess the final decision is made by the person that merges the pull request. But having three templates, let alone two is going to cause unbelievable head ache when it comes to making feature or bug fixes to the templates.

**Comment by Zemke** [comment]
Looks nice. I like the filter as well.

What do you think about putting the navigation on the right side? I see a couple of advantages for having it on the right side. It wouldn’t require so much space. It could just be on the right side and have an infinite width. It wouldn’t ever need to wrap any Angular component name and it doesn’t take as much space.

I agree with @reloaded. A single template that we focus on is probably more efficient.

**Comment by Zemke** [comment]
As a matter of fact the default template doesn’t even work for me. This is a blocker for other PRs and issues right now, so we should quickly find an agreement here.

//cc @allenhwkim

**Comment by reloaded** [comment]
@Zemke Actually, in my Angular project my module names are namespaced using the period separator and right now the navigation headers are line wrapping.

I prefer the navigation headers to be 15px instead of 30px and I prefer the navigation to be on the left side. I've never seen a navigation on the right side before, it feels like I'm reading documentation in RTL format. :)

**Comment by allenhwkim** [comment]
I agree with @Zemke
I prefer the navigation on the right side, and it has its advantage
If it goes to the left side, I believe that the template must be responsive, RWD, which isn't now.

Reference aboout right-side vs left-side navigation.
http://ux.stackexchange.com/questions/31031/how-to-choose-the-better-placement-for-sidebar-left-or-right
https://www.quora.com/How-do-UI-designers-decide-when-to-put-the-navigation-menu-on-the-right-Twitter-Quora-vs-the-left-Google-Reader-Facebook

I will leave to @Zemke to remove default template or not. 
For the maintenance sake, I want to keep one template only and I prefer angular-template, angular-like-template actually.

Thank you so much @reloaded and @Zemke to make this improved.

**Comment by Zemke** [comment]
We have three templates: default, angular-template and simple-searchable.

@allenhwkim, what do you mean with “angular-like”?

I’d remove default as it doesn’t work and it’s also many features behind the other two. Between the other two I’d pick simple-searchable because it has a clean look and the filter is a nice feature. But I’d definitely want the nav tone on the right.

So, what are your votes?

**Comment by zxuwen** [comment]
Not a big issue to put the navigation left or right...I can do that. Didn't bother to make the template responsive, because I didn't see too much of a use case for it, but I guess some support could be added for different screen sizes. Let me know if we want this, and I'll make the changes! Personally I much prefer the cleaner look, which is why I changed the styling.

**Comment by allenhwkim** [comment]
@Zemke`angular-like` means the template I made is html template not the exact angular template. e.g. `ht-repeat`, not `ng-repeat`.

I would leave @Zemke to pick one template and abandon others for easy maintenance.
about menu, I prefer right-side navigation

**Comment by Zemke** [comment]
Ah okay. I’m also a fan of `angular-template`. 😉
Fine, `simple-searchable` is built using `angular-template`. So, let’s pick this, but with nav on the right side.

@zxuwen, would you mind updating your PR with the nav on the right side? We’d then love to use it as the sole template of `allenhwkim/angular-jsdoc`.

Once this is merged, I’d love @reloaded to update his open PRs to apply to the `simple-searchable` template and then we can have a new nice release. 👍

**Comment by zxuwen** [comment]
Ok! Will do, over the weekend.

**Comment by zxuwen** [comment]
Hi, made a new pull request here:

https://github.com/allenhwkim/angular-jsdoc/pull/82

In the new PR, angular-template has been completely replaced and simple-searchable removed. Please take a look. 

Updated to have navbar on the right, removed the scrollable div within the navigation (to prevent double scrollable when both nav and contents overflow).

screen shot 2016-05-05 at 10 30 46 am

**Pull request closed without merging**
